# ==========================================
# Galactic Center Search Configuration
# ==========================================

# --- User & Paths ---
user: hoitim.cheung
home_dir: /home/hoitim.cheung/galacticCenter/
osdf_dir: /osdf/igwn/cit/staging/hoitim.cheung/

# Executables
executables:
  weave: /cvmfs/software.igwn.org/conda/envs/igwn-py39-20231212/bin/lalpulsar_Weave
  split_sfts: /cvmfs/software.igwn.org/conda/envs/igwn-py39-20231212/bin/lalpulsar_splitSFTs
  estimate_uls: /cvmfs/software.igwn.org/conda/envs/igwn-py39-20231212/bin/lalpulsar_ComputeFstatMCUpperLimit

# --- Data label ---
sft_source: C00-C01_Gated_G02_1800s

# --- Computing label ---
acc_group: ligo.prod.o4.cw.directedisolated.semicoherent

# --- Search Configuration Parameters ---
f0_band: 0.025   # Resolution of search in frequency
semi_mm: 0.2    # Maximum accepted mismatch of the semicoherent metric
coh_mm: 0.1     # Maximum accepted mismatch of the coherent metrics
num_top_list: 2000  # Number of top candidates to keep from the search job

# --- Injection & Follow-up ---
cluster_n_spacing: 4.0   # For injection and followUp
followup_n_spacing: 8.0  # For injection and followUp

# --- Braking index ---
nc_min: 2.0
nc_max: 7.0


